version: '3.4'

networks:
  default:
    external:
      name: host

services:
  roach0:
    image: cockroachdb/cockroach:v2.0.1
    command: 'start --insecure --cache=25% --max-sql-memory=25% --logtostderr'
    stop_grace_period: 1m
    volumes:
      - type: bind
        source: /volumes/cockroachdb/data
        target: /cockroach/cockroach-data
    deploy:
      placement:
        constraints:
          - node.hostname == mav-ubuntu-02
      resources:
        limits:
          cpus: '3'
          memory: '2G'
        reservations:
          cpus: '2.9'
          memory: '1.9G'

  roach1:
    image: cockroachdb/cockroach:v2.0.1
    command: 'start --insecure --cache=25% --max-sql-memory=25% --join=mav-ubuntu-01,mav-ubuntu-02,mav-ubuntu-03 --logtostderr'
    stop_grace_period: 1m
    volumes:
      - type: bind
        source: /volumes/cockroachdb/data
        target: /cockroach/cockroach-data
    deploy:
      placement:
        constraints:
          - node.hostname == mav-ubuntu-01
      resources:
        limits:
          cpus: '3'
          memory: '2G'
        reservations:
          cpus: '2.9'
          memory: '1.9G'

  roach2:
    image: cockroachdb/cockroach:v2.0.1
    command: 'start --insecure --cache=25% --max-sql-memory=25% --join=mav-ubuntu-01,mav-ubuntu-02,mav-ubuntu-03 --logtostderr'
    stop_grace_period: 1m
    volumes:
      - type: bind
        source: /volumes/cockroachdb/data
        target: /cockroach/cockroach-data
    deploy:
      placement:
        constraints:
          - node.hostname == mav-ubuntu-03
      resources:
        limits:
          cpus: '3'
          memory: '2G'
        reservations:
          cpus: '2.9'
          memory: '1.9G'
